dist: xenial
language: bash
sudo: false
install: true
addons:
  apt:
    packages:
    - lua5.1
    - lua-check

script:
  - luacheck oscl --codes --globals love --ignore "_.*"
  - lua test/test.lua


